services:
  urbanforge:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SITE_URL: ${SITE_URL:-http://localhost:3000}

    container_name: urbanforge-app

    ports:
      - "3000:3000"

    env_file:
      - .env

    restart: unless-stopped
