import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "@/components/cart/CartProvider";
import { FeedbackProvider } from "@/components/ui/Feedback";
import CookieNotice from "@/components/cookies/CookieNotice";
import QueryProvider from "@/components/providers/QueryProvider";
import { Inter } from 'next/font/google';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      {/* Browser extensions can inject attributes on body before React hydrates. */}
      <body suppressHydrationWarning className="bg-[#111111] text-white antialiased">
        <FeedbackProvider>
        <QueryProvider>
        <CartProvider>
          {children}
          <CookieNotice />
        </CartProvider>
        </QueryProvider>
        </FeedbackProvider>
      </body>
    </html>
  );
}
